SELECT CLASS, COUNTRY FROM CLASSES
WHERE NUMGUNS < 10;

SELECT NAME AS shipName FROM SHIPS
WHERE LAUNCHED < 1918;

SELECT SHIP, BATTLE FROM OUTCOMES
WHERE RESULT = 'sunk';

SELECT NAME FROM SHIPS
WHERE NAME = CLASS;

SELECT NAME FROM SHIPS
WHERE NAME LIKE 'R%';

SELECT NAME FROM SHIPS
WHERE NAME LIKE '% %';

SELECT NAME FROM SHIPS, CLASSES
WHERE SHIPS.CLASS = CLASSES.CLASS
AND CLASSES.DISPLACEMENT > 35000;

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, OUTCOMES
WHERE SHIPS.CLASS = CLASSES.CLASS
AND SHIPS.NAME = OUTCOMES.SHIP
AND OUTCOMES.BATTLE = 'Guadalcanal';

SELECT CBB.COUNTRY
FROM CLASSES CBB, CLASSES CBC
WHERE CBB.COUNTRY = CBC.COUNTRY
AND CBB.TYPE = 'bb' AND CBC.TYPE = 'bc';

-- II

SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';

SELECT OUTCOMES.BATTLE, CLASSES.COUNTRY, COUNT(SHIPS.NAME)
FROM CLASSES, SHIPS, OUTCOMES
WHERE CLASSES.CLASS = SHIPS.CLASS AND OUTCOMES.SHIP = SHIPS.NAME
GROUP BY OUTCOMES.BATTLE, CLASSES.COUNTRY
HAVING COUNT(SHIPS.NAME) = 3;

SELECT O1.SHIP, O1.BATTLE, B1.DATE, O2.SHIP, O2.BATTLE, B2.DATE
FROM OUTCOMES O1, BATTLES B1,
     OUTCOMES O2, BATTLES B2
WHERE O1.BATTLE = B1.NAME
AND   O2.BATTLE = B2.NAME
AND   O1.RESULT = 'damaged'
AND   B1.DATE < B2.DATE
AND   O1.SHIP = O2.SHIP;





SELECT CLASS, COUNTRY FROM CLASSES
WHERE NUMGUNS < 10;

SELECT NAME AS shipName FROM SHIPS
WHERE LAUNCHED < 1918;

SELECT SHIP, BATTLE FROM OUTCOMES
WHERE RESULT = 'sunk';

SELECT NAME FROM SHIPS
WHERE NAME = CLASS;

SELECT NAME FROM SHIPS
WHERE NAME LIKE 'R%';

SELECT NAME FROM SHIPS
WHERE NAME LIKE '% %';

SELECT NAME FROM SHIPS, CLASSES
WHERE SHIPS.CLASS = CLASSES.CLASS
AND CLASSES.DISPLACEMENT > 35000;

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, OUTCOMES
WHERE SHIPS.CLASS = CLASSES.CLASS
AND SHIPS.NAME = OUTCOMES.SHIP
AND OUTCOMES.BATTLE = 'Guadalcanal';

SELECT CBB.COUNTRY
FROM CLASSES CBB, CLASSES CBC
WHERE CBB.COUNTRY = CBC.COUNTRY
AND CBB.TYPE = 'bb' AND CBC.TYPE = 'bc';

-- II

SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';

SELECT OUTCOMES.BATTLE, CLASSES.COUNTRY, COUNT(SHIPS.NAME)
FROM CLASSES, SHIPS, OUTCOMES
WHERE CLASSES.CLASS = SHIPS.CLASS AND OUTCOMES.SHIP = SHIPS.NAME
GROUP BY OUTCOMES.BATTLE, CLASSES.COUNTRY
HAVING COUNT(SHIPS.NAME) = 3;

SELECT O1.SHIP, O1.BATTLE, B1.DATE, O2.SHIP, O2.BATTLE, B2.DATE
FROM OUTCOMES O1, BATTLES B1,
     OUTCOMES O2, BATTLES B2
WHERE O1.BATTLE = B1.NAME
AND   O2.BATTLE = B2.NAME
AND   O1.RESULT = 'damaged'
AND   B1.DATE < B2.DATE
AND   O1.SHIP = O2.SHIP;





