CREATE OR REPLACE PROCEDURE GetEmployeeInfo (IN employee_id_param INTEGER)
    LANGUAGE SQL
    READS SQL DATA
    DYNAMIC RESULT SETS 1
BEGIN
    DECLARE result_set CURSOR WITH RETURN TO CLIENT FOR
        SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
        FROM HW2_EMPLOYEES
        WHERE EMPLOYEE_ID = employee_id_param;

    OPEN result_set;
END;

CALL FN3MI0700050.GetEmployeeInfo(101);

CREATE OR REPLACE PROCEDURE GetEmployeeInfoWrapper (IN employee_id_param INTEGER)
    LANGUAGE SQL
    READS SQL DATA
    DYNAMIC RESULT SETS 1
BEGIN
    CALL FN3MI0700050.GetEmployeeInfo(employee_id_param);
END;

CALL FN3MI0700050.GetEmployeeInfoWrapper(101);




