-- PIZZAPRODUCT table
INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.5, 3.99, 'Tomatoes');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.6, 5.99, 'Pepperoni');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 6.99, 'Mushrooms');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 4.99, 'Pineapple');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 2.99, 'Olives');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.9, 2.99, 'BBQ Sauce');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 2.99, 'Bell Peppers');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.9, 5.99, 'Sausage');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 3.99, 'Garlic');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 4.99, 'Buffalo Sauce');

-- DRINK table
INSERT INTO DRINK (NAME, PRICE)
VALUES ('Coke', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Sprite', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Fanta', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Lemonade', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Iced Tea', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Root Beer', 1.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Water', 0.99);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Orange Juice', 2.49);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Limeade', 2.49);

INSERT INTO DRINK (NAME, PRICE)
VALUES ('Milk', 1.49);

-- PIZZA table
INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Margherita', 8.99, 0.5, 'Tomatoes');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Pepperoni', 9.99, 0.6, 'Pepperoni');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Mushroom', 10.99, 0.7, 'Mushrooms');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Hawaiian', 12.99, 0.8, 'Pineapple');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Supreme', 11.99, 0.7, 'Olives');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('BBQ Chicken', 13.99, 0.9, 'BBQ Sauce');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Vegetarian', 10.99, 0.8, 'Bell Peppers');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Meat Lovers', 14.99, 0.9, 'Sausage');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('White Pizza', 11.99, 0.7, 'Garlic');

INSERT INTO PIZZA (NAME, PRICE, WEIGHT, PRODUCT_NAME)
VALUES ('Buffalo Chicken', 13.99, 0.8, 'Buffalo Sauce');

-- CLIENT table
INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Alice Smith', '123 Main St', '+1 (123) 456-7890');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Bob Johnson', '456 Elm St', '+1 (234) 567-8901');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Eva Anderson', '789 Oak St', '+1 (345) 678-9012');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('John Davis', '987 Pine St', '+1 (456) 789-0123');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Sarah Wilson', '654 Maple St', '+1 (567) 890-1234');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('David Thompson', '321 Cedar St', '+1 (678) 901-2345');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Emily Brown', '987 Walnut St', '+1 (789) 012-3456');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Michael Evans', '654 Birch St', '+1 (890) 123-4567');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Laura Taylor', '321 Spruce St', '+1 (901) 234-5678');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Daniel Miller', '987 Pine St', '+1 (012) 345-6789');

-- ORDER table
INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (15.99, '+1 (123) 456-7890', 1, 1);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (12.99, '+1 (234) 567-8901', 2, 2);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (18.99, '+1 (345) 678-9012', 3, 1);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (14.99, '+1 (456) 789-0123', 4, 3);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (11.99, '+1 (567) 890-1234', 5, 2);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (16.99, '+1 (678) 901-2345', 6, 1);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (13.99, '+1 (789) 012-3456', 7, 3);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (17.99, '+1 (890) 123-4567', 8, 2);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (10.99, '+1 (901) 234-5678', 9, 1);

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID)
VALUES (19.99, '+1 (012) 345-6789', 10, 3);