-- PIZZAPRODUCT table
INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0, 0, 'None');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.5, 3.99, 'Tomatoes');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.6, 5.99, 'Pepperoni');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 6.99, 'Mushrooms');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 4.99, 'Pineapple');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 2.99, 'Olives');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.9, 2.99, 'BBQ Sauce');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 2.99, 'Bell Peppers');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.9, 5.99, 'Sausage');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.7, 3.99, 'Garlic');

INSERT INTO PIZZAPRODUCT (WEIGHT, PRICE, NAME)
VALUES (0.8, 4.99, 'Buffalo Sauce');

-- DRINK table
INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('None', 0, 0);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Coke', 0.500, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Sprite', 0.500, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Fanta', 0.500, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Lemonade', 0.400, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Iced Tea', 0.300, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Root Beer', 0.200, 1.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Water', 0.250, 0.99);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Orange Juice', 0.300, 2.49);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Limeade', 0.300, 2.49);

INSERT INTO DRINK (NAME, WEIGHT, PRICE)
VALUES ('Milk', 0.150, 1.49);

-- PIZZA table
INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('None', 0, 0);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Margherita', 8.99, 0.5);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Pepperoni', 9.99, 0.6);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Mushroom', 10.99, 0.7);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Hawaiian', 12.99, 0.8);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Supreme', 11.99, 0.7);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('BBQ Chicken', 13.99, 0.9);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Vegetarian', 10.99, 0.8);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Meat Lovers', 14.99, 0.9);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('White Pizza', 11.99, 0.7);

INSERT INTO PIZZA (NAME, PRICE, WEIGHT)
VALUES ('Buffalo Chicken', 13.99, 0.8);

-- CLIENT table
INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Alice Smith', '123 Main St', '+1 456-7890');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Bob Johnson', '456 Elm St', '+1 567-8901');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Eva Anderson', '789 Oak St', '+1 678-9012');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('John Davis', '987 Pine St', '+1 789-0123');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Sarah Wilson', '654 Maple St', '+1 890-1234');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('David Thompson', '321 Cedar St', '+1 901-2345');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Emily Brown', '987 Walnut St', '+1 012-3456');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Michael Evans', '654 Birch St', '+1 123-4567');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Laura Taylor', '321 Spruce St', '+1 234-5678');

INSERT INTO CLIENT (NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Daniel Miller', '987 Pine St', '+1 345-6789');

-- ORDER table
INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (15.99, '+1 456-7890', 1, 1, 'None');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (12.99, '+1 567-8901', 2, 2, 'Tomatoes');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (18.99, '+1 678-9012', 3, 1, 'Pepperoni');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (14.99, '+1 789-0123', 4, 3, 'Mushrooms');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (11.99, '+1 890-1234', 5, 2, 'Pineapple');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (16.99, '+1 901-2345', 6, 1, 'Olives');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (13.99, '+1 012-3456', 7, 3, 'BBQ Sauce');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (17.99, '+1 123-4567', 8, 2, 'Bell Peppers');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (10.99, '+1 234-5678', 9, 1, 'Sausage');

INSERT INTO ORDER (PRICE, CLIENT_PHONE_NUMBER, PIZZA_ID, DRINK_ID, PRODUCT_NAME)
VALUES (19.99, '+1 345-6789', 10, 3, 'Garlic');