SELECT ADDRESS FROM STUDIO
WHERE NAME = 'MGM';

SELECT BIRTHDATE FROM MOVIESTAR
WHERE NAME = 'Sandra Bullock';

SELECT NAME FROM MOVIESTAR, STARSIN
WHERE MOVIEYEAR = 1980
AND MOVIETITLE LIKE '%Love%';

SELECT NAME, TITLE FROM MOVIEEXEC, MOVIE
WHERE NETWORTH >= 10000000;

SELECT NAME FROM MOVIESTAR
WHERE GENDER = 'M'
OR ADDRESS LIKE '%Malibu%';

SELECT NAME AS STAR_NAME, MOVIETITLE FROM MOVIESTAR, STARSIN
WHERE STARSIN.STARNAME = MOVIESTAR.NAME
AND GENDER = 'M'
AND MOVIETITLE = 'Terms of Endearment';

SELECT MOVIESTAR.NAME FROM MOVIESTAR, STARSIN, MOVIE
WHERE MOVIESTAR.NAME = STARSIN.STARNAME
AND STARSIN.MOVIETITLE = MOVIE.TITLE
AND MOVIE.STUDIONAME = 'MGM'
AND MOVIE.YEAR = 1995;

SELECT MOVIEEXEC.NAME, MOVIE.TITLE, MOVIE.STUDIONAME
FROM MOVIEEXEC, MOVIE
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
AND MOVIE.STUDIONAME = 'MGM';

SELECT MOVIE.TITLE
FROM MOVIE, MOVIE GWTW
WHERE GWTW.TITLE = 'Gone With the Wind'
AND MOVIE.LENGTH > GWTW.LENGTH;

SELECT MOVIEEXEC.NAME
FROM MOVIEEXEC, MOVIEEXEC MV
WHERE MV.NAME = 'Merv Griffin'
AND MOVIEEXEC.NETWORTH > MV.NETWORTH;
